import { BaseService } from "./BaseService";

import { TfgRepository } from "../models/repositories/TfgRepository";
import { Tfg } from "../models/entities/Tfg";

import { TfgFormData } from "../shared/types/TfgFormData";
import { validateTfgFormData } from "../validators/TfgValidator";

import fs from "fs/promises";
import path from "path";
import yaml from "js-yaml";

export class TfgService extends BaseService<Tfg> {
  private tfgRepository: TfgRepository;

  constructor() {
    super(new TfgRepository());
    this.tfgRepository = new TfgRepository();
  }

  convertTfgFormDataToTfg(data: TfgFormData, userId: number): Tfg {
    return new Tfg(
      data.title,
      data.tutor,
      data.department,
      data.language,
      "",
      data.call.month,
      parseInt(data.call.year),
      userId,
      undefined, // bfp_id (default to null as is generated by RDBMS)
      data.subtitle || null, // subtitle (default to null if not provided)
      data.coTutor || null // coTutor (default to null if not provided)
    );
  }

  convertTfgToFormData(tfg: Tfg): TfgFormData {
    return {
      title: tfg.title,
      subtitle: tfg.subtitle || "",
      language: tfg.language,
      call: {
        month: tfg.month,
        year: tfg.year.toString(), // Convert year to string for consistency
      },
      tutor: tfg.tutor,
      coTutor: tfg.cotutor || "",
      department: tfg.department,
    };
  }

  async readConfigFile(dir: string): Promise<Record<string, any>> {
    let config: Record<string, any> = {};
    try {
      const content = await fs.readFile(path.join(dir, "config.yaml"), "utf-8");
      // First, we need to remove the "Cite: " line if it exists
      const lines = content
        .split("\n")
        .filter((line) => !line.startsWith("Cite:"));
      // Then, we can parse the remaining lines as YAML
      const filteredContent = lines.join("\n");
      config = yaml.load(filteredContent) as Record<string, any>;
      await fs.writeFile(
        path.join(dir, "config.yaml"),
        filteredContent,
        "utf-8"
      );
    } catch (error) {
      console.error("Error reading or parsing config file:", error);
      // Handle the error as needed, e.g., return an empty object or throw an error
      config = {};
    } finally {
      return config;
    }
  }

  async createNewTfg(data: TfgFormData, userId: number): Promise<Tfg> {
    try {
      // Validaciones QUE LAS MOVERÍA A CONTROLADOR
      validateTfgFormData(data);
      // Lógica de negocio
      const convTfg = this.convertTfgFormDataToTfg(data, userId);

      if (!convTfg.isComplete()) {
        throw new Error("TFG data is incomplete (CHECK VALIDATION).");
      }

      if (convTfg.csl.trim() === "") {
        // If CSL is not provided, set a default value
        const defaultCsl = "acm-sig-proceedings"; // Default CSL style
        convTfg.csl = defaultCsl;
        console.log("Setting default CSL style:", defaultCsl);
      }

      const response = await this.tfgRepository.create(convTfg);
      if (!response || !response.bfp_id) {
        throw new Error("Failed to create new TFG.");
      }

      convTfg.bfp_id = response.bfp_id; // Set the generated id to the TFG object

      console.log("New TFG created with id:", convTfg.bfp_id);
      return convTfg;
    } catch (error) {
      console.error("Error creating new TFG:", error);
      throw new Error(`Failed to create TFG: ${error}`);
    }
  }

  async findById(id: number): Promise<Tfg | null> {
    return this.tfgRepository.findById(id);
  }

  async updateTfg(id: number, data: Partial<TfgFormData>): Promise<Tfg> {
    try {
      // Validaciones QUE LAS MOVERÍA A CONTROLADOR
      validateTfgFormData(data as TfgFormData);

      // Lógica de negocio
      const tfg = await this.tfgRepository.findById(id);
      if (!tfg) {
        throw new Error(`TFG with ID ${id} not found.`);
      }

      // Update fields based on provided data
      if (data.title) tfg.title = data.title;
      if (data.subtitle) tfg.subtitle = data.subtitle;
      if (data.tutor) tfg.tutor = data.tutor;
      if (data.coTutor) tfg.cotutor = data.coTutor;
      if (data.department) tfg.department = data.department;
      if (data.language) tfg.language = data.language;
      if (data.call) {
        tfg.month = data.call.month;
        tfg.year = parseInt(data.call.year);
      }

      const updatedTfg = await this.tfgRepository.update(id, tfg);
      return updatedTfg;
    } catch (error) {
      console.error("Error updating TFG:", error);
      throw new Error(`Failed to update TFG: ${error}`);
    }
  }

  async updateCslTfg(id: number, csl: string): Promise<Tfg> {
    try {
      const tfg = await this.tfgRepository.findById(id);
      if (!tfg) {
        throw new Error(`TFG with ID ${id} not found.`);
      }
      tfg.csl = csl;

      const updatedTfg = await this.tfgRepository.update(id, tfg);
      return updatedTfg;
    } catch (error) {
      console.error("Error updating TFG CSL:", error);
      throw new Error(`Failed to update TFG CSL: ${error}`);
    }
  }
}
