import { PoolClient } from "pg";
import { insertUserQuery } from "@db/queries/userQueries";

/**
 * Inserts user data into the database.
 * @param client the database client to use for the operation.
 * @param userArray the array containing user data to be inserted, according to the query format.
 * @returns {Promise<any>} A promise that resolves to the user_id of the inserted user.
 * @throws {Error} If the insertion fails or if no rows are affected.
 */

export async function insertUserData(
  client: PoolClient,
  userArray: (string | number | null)[]
): Promise<any> {
  // Remove the first element (user_id) from the array, even if it is undefined
  // This is because the user_id will be generated by the database
  let user_id = userArray.shift();
  console.log(`Inserting user ${userArray}`);
  // Insert user data
  const userResult = await client.query(insertUserQuery, userArray);
  if (userResult.rowCount === 0) {
    throw new Error("Failed to insert user data.");
  }
  user_id = userResult.rows[0].user_id; // Get the generated user_id
  console.log("User data inserted successfully with user_id:", user_id);
  return user_id;
}
