import pool from "../../config/pool";
import { constructTFG } from "./defaultTfgConstruct";
import { parseAcronymFile } from "../parse/acronymParser";
import { insertUserQuery } from "../../queries/userQueries";
import { insertTfgQuery } from "../../queries/tfgQueries";
import { insertBasicInfoQuery } from "../../queries/basicInfoQueries";
import { insertChapterQuery } from "../../queries/chapterQueries";
import { insertAppendixQuery } from "../../queries/appendixQueries";
import { insertResourceQuery } from "../../queries/imageQueries";
import { insertAcronymQuery } from "../../queries/acronymQueries";

import { User } from "../../models/User";
import { TFG } from "../../models/Tfg";
import { PoolClient } from "pg";

async function insertChapters(
  chapters: any,
  bfp_id: any,
  client: PoolClient
): Promise<void> {
  for (const [number, data] of Object.entries(chapters)) {
    const { title, content }: { title: string; content: string } = data as {
      title: string;
      content: string;
    };
    const chapter_id = (
      bfp_id +
      "_ch_" +
      title.toLowerCase().replace(/\s+/g, "_")
    ).slice(0, 64);
    const chapterData = [
      chapter_id,
      title,
      10 * parseInt(number), // This will help to swap values
      content,
      bfp_id,
    ];
    console.log("Inserting chapter data:", chapterData);
    await client.query(insertChapterQuery, chapterData);
  }
}

async function insertAppendices(
  appendices: any,
  bfp_id: any,
  client: PoolClient
): Promise<void> {
  for (const [number, data] of Object.entries(appendices)) {
    const { title, content }: { title: string; content: string } = data as {
      title: string;
      content: string;
    };
    const appendix_id = (
      bfp_id +
      "_ap_" +
      title.toLowerCase().replace(/\s+/g, "_")
    ).slice(0, 64);
    const appendixData = [
      appendix_id,
      title,
      10 * parseInt(number), // This will help to swap values
      content,
      bfp_id,
    ];
    console.log("Inserting appendix data:", appendixData);
    await client.query(insertAppendixQuery, appendixData);
  }
}

async function insertBasicInfo(
  client: PoolClient,
  basicInfoArray: (string | number | null)[]
): Promise<void> {
  console.log("Inserting basic info data:", basicInfoArray);
  const basicInfoResult = await client.query(
    insertBasicInfoQuery,
    basicInfoArray
  );
  if (basicInfoResult.rowCount === 0) {
    throw new Error("Failed to insert basic info data.");
  }
  console.log("Basic info data inserted successfully.");
}

async function insertTFGData(
  client: PoolClient,
  tfgArray: (string | number | null)[]
): Promise<any> {
  // Remove the first element (bfp_id) from the array
  let bfp_id = tfgArray.shift();
  console.log(`Inserting TFG `, tfgArray);
  const tfgResult = await client.query(insertTfgQuery, tfgArray);
  if (tfgResult.rowCount === 0) {
    throw new Error("Failed to insert TFG data.");
  }
  bfp_id = tfgResult.rows[0].bfp_id; // Get the generated bfp_id
  console.log("TFG data inserted successfully with bfp_id:", bfp_id);
  return bfp_id;
}

/**
 * Inserts user data into the database.
 * @param client the database client to use for the operation.
 * @param userArray the array containing user data to be inserted, according to the query format.
 * @returns {Promise<any>} A promise that resolves to the user_id of the inserted user.
 * @throws {Error} If the insertion fails or if no rows are affected.
 */

async function insertUserData(
  client: PoolClient,
  userArray: (string | number | null)[]
): Promise<any> {
  // Remove the first element (user_id) from the array, even if it is undefined
  // This is because the user_id will be generated by the database
  let user_id = userArray.shift();
  console.log(`Inserting user ${userArray}`);
  // Insert user data
  const userResult = await client.query(insertUserQuery, userArray);
  if (userResult.rowCount === 0) {
    throw new Error("Failed to insert user data.");
  }
  user_id = userResult.rows[0].user_id; // Get the generated user_id
  console.log("User data inserted successfully with user_id:", user_id);
  return user_id;
}

/**
 * Creates a new user and initializes their TFG and basic info in the database.
 * @param {Object} userData - The user data to insert.
 * @param {Object} tfgData - The TFG data to insert.
 * @returns {Promise<void>}
 * @throws {Error} If an error occurs during the database operations.
 */

export async function initNewUser(userData: User, tfgData: TFG): Promise<void> {
  const client = await pool.connect();
  try {
    const data = await constructTFG();
    if (!data) {
      throw new Error("Failed to initialize user data.");
    }
    await client.query("BEGIN");

    const chapters = data.chapters;
    const appendices = data.appendices;
    const setup = data.setupFiles;
    const acronyms = parseAcronymFile(setup.acronyms);
    const res = data.resources;
    const cfg = data.config;
    const bib = data.bibliography;

    // Ensure TFG data is correct before inserting
    tfgData.csl = cfg.Csl.split("/").pop().split(".")[0]; // Filename without route and extension
    tfgData.month = tfgData.month ? tfgData.month : "JUNIO"; // Assuming the creation of a TFG is in ordinary (June)
    tfgData.year = tfgData.year ? tfgData.year : new Date().getFullYear(); // Current year

    const bfp_id = await insertTFGData(client, tfgData.toArray());

    // Insert basic info data
    const basicInfoArray = [
      "cfg_" + userData.user_id, // cfg_id == user_id FOR THE MOMENT
      bfp_id,
      setup.abstract,
      setup.acknowledgements,
      setup.autorship,
      setup.dedication,
      setup.resumen,
      bib,
    ];
    await insertBasicInfo(client, basicInfoArray);

    // Insert acronyms (obtain iterator from acronyms object)
    for (const [key, meaning] of Object.entries(acronyms)) {
      await client.query(insertAcronymQuery, [key, bfp_id, meaning]);
    }

    // Insert chapters and appendices
    await insertChapters(chapters, bfp_id, client);
    await insertAppendices(appendices, bfp_id, client);

    // Insert resources (images)
    for (const [filename, data] of Object.entries(res)) {
      const resourceData = [filename, data, bfp_id];
      console.log("Inserting resource data:", resourceData);
      await client.query(insertResourceQuery, resourceData);
    }

    await client.query("COMMIT");
    console.log("TFG initialized successfully for user:", userData.user_id);
  } catch (error) {
    console.error("Error creating and initializing user:\n", error);
    await client.query("ROLLBACK");
    throw error;
  } finally {
    client.release();
  }
}

export async function createNewUser(userData: any): Promise<User> {
  try {
    const user = new User(
      userData.email,
      userData.name,
      userData.password,
      userData.lastNames[0], // lastname1 (first element of lastNames array)
      userData.lastNames[1], // lastname2 (second element of lastNames array or empty string)
      userData.technology,
      undefined, // user_id should be provided by the RDBMS
      userData.phone || null // phone (default to null if not provided)
    );

    if (!user) {
      throw new Error("Failed to create User object.");
    }
    const client = await pool.connect();
    const new_user_id = await insertUserData(client, user.toArray());
    client.release();
    user.user_id = new_user_id; // Set the generated user_id to the User object
    console.log("New user created with user_id:", user.user_id);
    return user;
  } catch (error) {
    console.error("Error initializing new user:", error);
    throw error;
  }
}

export async function createNewTFG(
  new_user_id: number,
  tfgData: any
): Promise<TFG> {
  try {
    const tfg = new TFG(
      tfgData.title,
      tfgData.tutor,
      tfgData.department,
      tfgData.language,
      "", // csl (default value, assuming it will be set later)
      tfgData.call.month,
      parseInt(tfgData.call.year), // year (converted to number)
      new_user_id, // student (user_id)
      undefined, // bfp_id (default to null as is generated by the database)
      tfgData.subtitle || null, // subtitle (default to null if not provided)
      tfgData.coTutor || null // cotutor (default to null if not provided)
    );
    if (!tfg) {
      throw new Error("Failed to create TFG object.");
    }
    return tfg;
  } catch (error) {
    console.error("Error initializing new TFG:", error);
    throw error;
  }
}
